=begin
#Fluxo Client Credentials

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.24
=end

require 'spec_helper'
require 'json'

# Unit tests for BancoBrasilClientCredentials::DefaultApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @instance = BancoBrasilClientCredentials::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@instance).to be_instance_of(BancoBrasilClientCredentials::DefaultApi)
    end
  end

  # unit tests for oauth_token_post
  # @param grant_type 
  # @param scope 
  # @param authorization Deverá ser informado no padrão: Basic {Base64(client_id:client_secret)}
  # @param content_type Deverá ser informado:  application/x-www-form-urlencoded 
  # @param [Hash] opts the optional parameters
  # @return [RespostaToken]
  describe 'oauth_token_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
