=begin
#Fluxo Client Credentials

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.24
=end

# Common files
require 'bb_oauth/api_client'
require 'bb_oauth/api_error'
require 'bb_oauth/version'
require 'bb_oauth/configuration'

# Models
require 'bb_oauth/models/body'
require 'bb_oauth/models/resposta_token'

# APIs
require 'bb_oauth/api/default_api'

module BancoBrasilClientCredentials
  class << self
    # Customize default settings for the SDK using block.
    #   BancoBrasilClientCredentials.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
